replicaCount: 3

service:
  type: ClusterIP

ingress:
  enabled: false

wordpressUsername: student
wordpressEmail: student@example.local
wordpressBlogName: Kubernetes Course Blog

persistence:
  enabled: true
  size: 2Gi

mariadb:
  auth:
    database: bitnami_wordpress
    username: bn_wordpress
  primary:
    persistence:
      enabled: true
      size: 2Gi
