apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-demo
  namespace: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-demo
  template:
    metadata:
      labels:
        app: metrics-demo
    spec:
      containers:
        - name: metrics-demo
          image: module6/metrics-demo:local
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: MESSAGE
              value: module-6-metrics-demo
