apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-observability
  namespace: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami-observability
  template:
    metadata:
      labels:
        app: whoami-observability
    spec:
      containers:
        - name: whoami
          image: module4/whoami-python:local
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: MESSAGE
              value: module-6-probes-demo
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
