apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo-app.orders.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: orders-service
    {{- include "demo-app.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/component: orders-service
    {{- include "demo-app.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.ordersService.service.port }}
      targetPort: {{ .Values.ordersService.containerPort }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "demo-app.orders.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: orders-service
    {{- include "demo-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.ordersService.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: orders-service
      {{- include "demo-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: orders-service
        {{- include "demo-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: orders-service
          image: "{{ .Values.ordersService.image.repository }}:{{ .Values.ordersService.image.tag }}"
          imagePullPolicy: {{ .Values.ordersService.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.ordersService.containerPort }}
          env:
            - name: PORT
              value: {{ .Values.ordersService.containerPort | quote }}
            - name: CATALOG_URL
              value: http://{{ include "demo-app.catalog.fullname" . }}:{{ .Values.catalogService.service.port }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "demo-app.databaseSecret.fullname" . }}
                  key: DATABASE_URL
