apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo-app.postgres.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: postgres
    {{- include "demo-app.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/component: postgres
    {{- include "demo-app.selectorLabels" . | nindent 4 }}
  ports:
    - name: postgres
      port: {{ .Values.postgres.service.port }}
      targetPort: {{ .Values.postgres.containerPort }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "demo-app.postgres.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: postgres
    {{- include "demo-app.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "demo-app.postgres.fullname" . }}
  replicas: {{ .Values.postgres.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: postgres
      {{- include "demo-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: postgres
        {{- include "demo-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ include "demo-app.databaseSecret.fullname" . }}
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "demo-app.databaseSecret.fullname" . }}
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "demo-app.databaseSecret.fullname" . }}
                  key: POSTGRES_PASSWORD
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: {{ .Values.postgres.containerPort }}
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: postgres-init
              mountPath: /docker-entrypoint-initdb.d/init.sql
              subPath: init.sql
              readOnly: true
      volumes:
        - name: postgres-init
          configMap:
            name: {{ include "demo-app.postgresInit.fullname" . }}
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
        labels:
          {{- include "demo-app.labels" . | nindent 10 }}
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.postgres.persistence.size }}
