apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "whoami-python.fullname" . }}
  labels:
    {{- include "whoami-python.labels" . | nindent 4 }}
data:
  PORT: "8080"
  MESSAGE: {{ .Values.message | quote }}
