replicas: 1

service:
  type: ClusterIP
  port: 80

persistence:
  enabled: false

adminUser: admin
adminPassword: admin12345

grafana.ini:
  server:
    root_url: http://grafana.local
  users:
    allow_sign_up: false

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server.monitoring.svc.cluster.local
        isDefault: true
