apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  namespace: demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
        - name: whoami
          image: module2/whoami:local
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: MY_ENV_VAR
              value: module-2-demo
