apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: whoami-kustomize-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/irespaldiza/kubernetes_course.git
    targetRevision: main
    path: module-7/examples/kustomize/whoami-python/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
