apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo-app
resources:
  - namespace.yaml
  - database-secret.yaml
  - frontend-configmap.yaml
  - postgres-init-configmap.yaml
  - frontend.yaml
  - catalog-service.yaml
  - orders-service.yaml
  - postgres.yaml
