apiVersion: v1
kind: Pod
metadata:
  name: whoami-emptydir
  namespace: demo-app
spec:
  volumes:
    - name: workspace
      emptyDir: {}
  initContainers:
    - name: seed-workspace
      image: busybox:1.36
      command:
        - sh
        - -c
        - |
          echo "initialized by init container" > /workspace/startup.txt
          date >> /workspace/startup.txt
      volumeMounts:
        - name: workspace
          mountPath: /workspace
  containers:
    - name: whoami
      image: module4/whoami-python:local
      imagePullPolicy: Never
      ports:
        - containerPort: 8080
      env:
        - name: PORT
          value: "8080"
        - name: MESSAGE
          value: module-5-emptydir-demo
      volumeMounts:
        - name: workspace
          mountPath: /workspace
