apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
  namespace: demo-app
spec:
  rules:
    - host: frontend.demo.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
